import type { Store, Product, Service, Review, Plan, CartItem, PurchaseList } from "./types"

export const mockStores: Store[] = [
  {
    id: "1",
    nome: "Construmax",
    cnpj: "12.345.678/0001-90",
    status: "ativo",
    priorityScore: 95,
    plano: "Pro",
    createdAt: "2024-01-15",
    shippingPolicy: {
      type: "free",
    },
    address: {
      lat: -15.7942,
      lng: -47.8822,
      cidade: "Brasília",
      estado: "DF",
    },
  },
  {
    id: "2",
    nome: "Casa & Obra",
    cnpj: "98.765.432/0001-10",
    status: "ativo",
    priorityScore: 88,
    plano: "Basic",
    createdAt: "2024-02-20",
    shippingPolicy: {
      type: "free_radius",
      freeRadius: 10,
      pricePerKm: 3.5,
    },
    address: {
      lat: -15.7801,
      lng: -47.9292,
      cidade: "Brasília",
      estado: "DF",
    },
  },
  {
    id: "3",
    nome: "Materiais Silva",
    cnpj: "11.222.333/0001-44",
    status: "ativo",
    priorityScore: 82,
    plano: "Pro",
    createdAt: "2024-03-10",
    shippingPolicy: {
      type: "free_radius",
      freeRadius: 5,
      pricePerKm: 2.8,
      minOrderForFreeShipping: 500,
    },
    address: {
      lat: -15.7975,
      lng: -47.8919,
      cidade: "Brasília",
      estado: "DF",
    },
  },
  {
    id: "4",
    nome: "Depot Construção",
    cnpj: "55.666.777/0001-88",
    status: "suspended",
    priorityScore: 75,
    plano: "Basic",
    createdAt: "2024-01-05",
    shippingPolicy: {
      type: "fixed",
      fixedPrice: 50,
    },
    address: {
      lat: -15.8267,
      lng: -47.9218,
      cidade: "Brasília",
      estado: "DF",
    },
  },
  {
    id: "5",
    nome: "Mega Materiais",
    cnpj: "33.444.555/0001-22",
    status: "ativo",
    priorityScore: 90,
    plano: "Pro",
    createdAt: "2024-02-28",
    shippingPolicy: {
      type: "per_km",
      pricePerKm: 4.2,
    },
    address: {
      lat: -15.7655,
      lng: -47.8783,
      cidade: "Brasília",
      estado: "DF",
    },
  },
  {
    id: "6",
    nome: "Construir Mais",
    cnpj: "77.888.999/0001-33",
    status: "ativo",
    priorityScore: 85,
    plano: "Basic",
    createdAt: "2024-03-15",
    shippingPolicy: {
      type: "fixed",
      fixedPrice: 35,
      minOrderForFreeShipping: 800,
    },
    address: {
      lat: -15.8102,
      lng: -47.8976,
      cidade: "Brasília",
      estado: "DF",
    },
  },
  {
    id: "7",
    nome: "Ferro & Cimento",
    cnpj: "22.333.444/0001-55",
    status: "ativo",
    priorityScore: 78,
    plano: "Pro",
    createdAt: "2024-01-25",
    shippingPolicy: {
      type: "free_radius",
      freeRadius: 15,
      pricePerKm: 3.0,
    },
    address: {
      lat: -15.7689,
      lng: -47.9123,
      cidade: "Brasília",
      estado: "DF",
    },
  },
  {
    id: "8",
    nome: "Obra Prima",
    cnpj: "66.777.888/0001-99",
    status: "ativo",
    priorityScore: 92,
    plano: "Pro",
    createdAt: "2024-02-10",
    shippingPolicy: {
      type: "free",
    },
    address: {
      lat: -15.7883,
      lng: -47.8665,
      cidade: "Brasília",
      estado: "DF",
    },
  },
  {
    id: "9",
    nome: "Construção Total",
    cnpj: "44.555.666/0001-77",
    status: "ativo",
    priorityScore: 80,
    plano: "Basic",
    createdAt: "2024-03-05",
    shippingPolicy: {
      type: "per_km",
      pricePerKm: 3.8,
      minOrderForFreeShipping: 1000,
    },
    address: {
      lat: -15.8345,
      lng: -47.9045,
      cidade: "Brasília",
      estado: "DF",
    },
  },
  {
    id: "10",
    nome: "Material Express",
    cnpj: "99.000.111/0001-66",
    status: "ativo",
    priorityScore: 87,
    plano: "Pro",
    createdAt: "2024-01-30",
    shippingPolicy: {
      type: "fixed",
      fixedPrice: 45,
    },
    address: {
      lat: -15.7512,
      lng: -47.8901,
      cidade: "Brasília",
      estado: "DF",
    },
  },
]

export const mockProducts: Product[] = [
  // ========== PRODUTOS COM IMAGENS REAIS (PRIORIDADE) ==========
  
  // Cimento com imagens reais
  {
    id: "p1",
    storeId: "1",
    storeNome: "Construmax",
    nome: "Cimento Portland CP II-E 50kg",
    categoria: "Cimento",
    preco: 28.9,
    estoque: 150,
    unidadeMedida: "Saco (sc)",
    rating: 4.8,
    imagemUrl: "/mock/cimento-forte.png",
    sku: "CIM-001-CMX",
    ativo: true,
  },
  {
    id: "p2",
    storeId: "2",
    storeNome: "Casa & Obra",
    nome: "Cimento Portland CP II-E 50kg",
    categoria: "Cimento",
    preco: 29.5,
    estoque: 80,
    rating: 4.6,
    imagemUrl: "/mock/cimento-votoran.png",
    ativo: true,
  },
  {
    id: "p3",
    storeId: "3",
    storeNome: "Materiais Silva",
    nome: "Cimento Portland CP II-E 50kg",
    categoria: "Cimento",
    preco: 27.8,
    estoque: 200,
    rating: 4.9,
    imagemUrl: "/mock/cimento-forte.png",
    ativo: true,
  },
  // Tijolos com imagens reais
  {
    id: "p4",
    storeId: "1",
    storeNome: "Construmax",
    nome: "Tijolo Cerâmico 8 Furos 9x14x19cm",
    categoria: "Tijolos",
    preco: 0.85,
    estoque: 5000,
    rating: 4.7,
    imagemUrl: "/mock/tijolo-8-furos.png",
    ativo: true,
  },
  {
    id: "p5",
    storeId: "4",
    storeNome: "Depot Construção",
    nome: "Tijolo Cerâmico 8 Furos 9x14x19cm",
    categoria: "Tijolos",
    preco: 0.92,
    estoque: 3000,
    rating: 4.5,
    imagemUrl: "/mock/tijolo-8-furos.png",
    ativo: true,
  },
  // Areia com imagens reais
  {
    id: "p6",
    storeId: "5",
    storeNome: "Mega Materiais",
    nome: "Areia Média Lavada - m³",
    categoria: "Areia",
    preco: 45.0,
    estoque: 50,
    rating: 4.4,
    imagemUrl: "/mock/areia-media-lavada.png",
    ativo: true,
  },
  {
    id: "p7",
    storeId: "6",
    storeNome: "Construir Mais",
    nome: "Areia Média Lavada - m³",
    categoria: "Areia",
    preco: 42.5,
    estoque: 30,
    rating: 4.6,
    imagemUrl: "/mock/areia-media-lavada.png",
    ativo: true,
  },
  // Vergalhão com imagens reais
  {
    id: "p8",
    storeId: "7",
    storeNome: "Ferro & Cimento",
    nome: "Vergalhão CA-50 8mm - 12m",
    categoria: "Ferro",
    preco: 32.8,
    estoque: 120,
    rating: 4.8,
    imagemUrl: "/mock/vergalhao-8mm.png",
    ativo: true,
  },
  {
    id: "p9",
    storeId: "8",
    storeNome: "Obra Prima",
    nome: "Vergalhão CA-50 8mm - 12m",
    categoria: "Ferro",
    preco: 31.9,
    estoque: 200,
    rating: 4.9,
    imagemUrl: "/mock/vergalhao-8mm.png",
    ativo: true,
  },
  // Brita com imagens reais
  {
    id: "p10",
    storeId: "1",
    storeNome: "Construmax",
    nome: "Brita 1 - m³",
    categoria: "Brita",
    preco: 55.0,
    estoque: 25,
    rating: 4.5,
    imagemUrl: "/mock/brita.png",
    ativo: true,
  },
  {
    id: "p25",
    storeId: "10",
    storeNome: "Material Express",
    nome: "Pedra Britada 2 - m³",
    categoria: "Brita",
    preco: 58.0,
    estoque: 35,
    rating: 4.6,
    imagemUrl: "/mock/brita.png",
    ativo: true,
  },
  // Piso com imagens reais
  {
    id: "p16",
    storeId: "1",
    storeNome: "Construmax",
    nome: "Piso Cerâmico 45x45cm Acetinado",
    categoria: "Pisos",
    preco: 18.9,
    estoque: 350,
    rating: 4.8,
    imagemUrl: "/mock/piso-ceramico-45x45(acetinado).png",
    ativo: true,
  },
  {
    id: "p26",
    storeId: "1",
    storeNome: "Construmax",
    nome: "Piso Cerâmico 45x45cm Texturizado",
    categoria: "Pisos",
    preco: 24.9,
    estoque: 450,
    rating: 4.7,
    imagemUrl: "/mock/piso-ceramico-45x45(texturizado).png",
    ativo: true,
  },
  // Janela com imagens reais
  {
    id: "p20",
    storeId: "5",
    storeNome: "Mega Materiais",
    nome: "Janela de Alumínio 100x150cm",
    categoria: "Janelas",
    preco: 345.0,
    estoque: 25,
    rating: 4.8,
    imagemUrl: "/mock/janela-aluminio-100x150.png",
    ativo: true,
  },
  
  // ========== PRODUTOS SEM IMAGENS (AGUARDANDO FOTOS REAIS) ==========
  
  // Telhas
  {
    id: "p11",
    storeId: "2",
    storeNome: "Casa & Obra",
    nome: "Telha Cerâmica Portuguesa",
    categoria: "Telhas",
    preco: 2.8,
    estoque: 800,
    rating: 4.3,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p28",
    storeId: "3",
    storeNome: "Materiais Silva",
    nome: "Telha Metálica Trapezoidal",
    categoria: "Telhas",
    preco: 38.5,
    estoque: 120,
    rating: 4.8,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  // Tintas
  {
    id: "p12",
    storeId: "3",
    storeNome: "Materiais Silva",
    nome: "Tinta Acrílica Branca 18L",
    categoria: "Tintas",
    preco: 89.9,
    estoque: 45,
    rating: 4.7,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p21",
    storeId: "6",
    storeNome: "Construir Mais",
    nome: "Tinta Látex Fosca Branca 18L",
    categoria: "Tintas",
    preco: 95.9,
    estoque: 60,
    rating: 4.6,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  // Cal
  {
    id: "p13",
    storeId: "5",
    storeNome: "Mega Materiais",
    nome: "Cal Hidratada 20kg",
    categoria: "Cal",
    preco: 15.9,
    estoque: 200,
    rating: 4.6,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  // Blocos
  {
    id: "p14",
    storeId: "6",
    storeNome: "Construir Mais",
    nome: "Bloco de Concreto 14x19x39cm",
    categoria: "Blocos",
    preco: 3.5,
    estoque: 1500,
    rating: 4.5,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  // Argamassa
  {
    id: "p15",
    storeId: "7",
    storeNome: "Ferro & Cimento",
    nome: "Argamassa AC-III 20kg",
    categoria: "Argamassa",
    preco: 22.5,
    estoque: 180,
    rating: 4.7,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p27",
    storeId: "2",
    storeNome: "Casa & Obra",
    nome: "Argamassa Colante AC-II 20kg",
    categoria: "Argamassa",
    preco: 19.9,
    estoque: 220,
    rating: 4.5,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  // Madeira
  {
    id: "p17",
    storeId: "2",
    storeNome: "Casa & Obra",
    nome: "Madeira Pinus Tratado 3m",
    categoria: "Madeira",
    preco: 45.9,
    estoque: 90,
    rating: 4.6,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  // Tubos
  {
    id: "p18",
    storeId: "3",
    storeNome: "Materiais Silva",
    nome: "Tubo PVC 100mm 6m",
    categoria: "Tubos",
    preco: 28.5,
    estoque: 120,
    rating: 4.5,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  // Portas
  {
    id: "p19",
    storeId: "4",
    storeNome: "Depot Construção",
    nome: "Porta de Madeira Lisa 80x210cm",
    categoria: "Portas",
    preco: 289.9,
    estoque: 15,
    rating: 4.7,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p30",
    storeId: "5",
    storeNome: "Mega Materiais",
    nome: "Porta de Aço 80x210cm",
    categoria: "Portas",
    preco: 425.0,
    estoque: 18,
    rating: 4.9,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  // Elétricos
  {
    id: "p22",
    storeId: "7",
    storeNome: "Ferro & Cimento",
    nome: "Fio de Cobre 2.5mm 100m",
    categoria: "Elétricos",
    preco: 185.0,
    estoque: 40,
    rating: 4.9,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  // Lajes
  {
    id: "p23",
    storeId: "8",
    storeNome: "Obra Prima",
    nome: "Laje Treliçada H12",
    categoria: "Lajes",
    preco: 42.0,
    estoque: 150,
    rating: 4.7,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  // Metais
  {
    id: "p24",
    storeId: "9",
    storeNome: "Construção Total",
    nome: "Torneira Cromada com Arejador",
    categoria: "Metais",
    preco: 78.9,
    estoque: 85,
    rating: 4.5,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  // Vigas
  {
    id: "p29",
    storeId: "4",
    storeNome: "Depot Construção",
    nome: "Viga de Concreto 3m",
    categoria: "Vigas",
    preco: 125.0,
    estoque: 45,
    rating: 4.7,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  
  // ========== MAIS PRODUTOS PARA SCROLL ==========
  
  // Mais Cimento
  {
    id: "p51",
    storeId: "5",
    storeNome: "Mega Materiais",
    nome: "Cimento Portland CP III 50kg",
    categoria: "Cimento",
    preco: 31.5,
    estoque: 120,
    rating: 4.7,
    imagemUrl: "/mock/cimento-forte.png",
    ativo: true,
  },
  {
    id: "p52",
    storeId: "6",
    storeNome: "Construir Mais",
    nome: "Cimento Portland CP IV 50kg",
    categoria: "Cimento",
    preco: 33.0,
    estoque: 90,
    rating: 4.8,
    imagemUrl: "/mock/cimento-votoran.png",
    ativo: true,
  },
  {
    id: "p53",
    storeId: "7",
    storeNome: "Ferro & Cimento",
    nome: "Cimento Branco Estrutural 50kg",
    categoria: "Cimento",
    preco: 42.5,
    estoque: 60,
    rating: 4.9,
    imagemUrl: "/mock/cimento-forte.png",
    ativo: true,
  },
  {
    id: "p54",
    storeId: "8",
    storeNome: "Obra Prima",
    nome: "Cimento Portland CP V ARI 50kg",
    categoria: "Cimento",
    preco: 35.9,
    estoque: 110,
    rating: 4.6,
    imagemUrl: "/mock/cimento-votoran.png",
    ativo: true,
  },
  
  // Mais Tijolos
  {
    id: "p55",
    storeId: "1",
    storeNome: "Construmax",
    nome: "Tijolo Maciço 5x10x20cm",
    categoria: "Tijolos",
    preco: 1.2,
    estoque: 3000,
    rating: 4.5,
    imagemUrl: "/mock/tijolo-8-furos.png",
    ativo: true,
  },
  {
    id: "p56",
    storeId: "2",
    storeNome: "Casa & Obra",
    nome: "Tijolo Laminado 6 Furos",
    categoria: "Tijolos",
    preco: 0.95,
    estoque: 4500,
    rating: 4.7,
    imagemUrl: "/mock/tijolo-8-furos.png",
    ativo: true,
  },
  {
    id: "p57",
    storeId: "3",
    storeNome: "Materiais Silva",
    nome: "Tijolo Refratário 22x11x7cm",
    categoria: "Tijolos",
    preco: 3.8,
    estoque: 800,
    rating: 4.8,
    imagemUrl: "/mock/tijolo-8-furos.png",
    ativo: true,
  },
  {
    id: "p58",
    storeId: "5",
    storeNome: "Mega Materiais",
    nome: "Tijolo de Vidro 19x19x8cm",
    categoria: "Tijolos",
    preco: 5.5,
    estoque: 1200,
    rating: 4.6,
    imagemUrl: "/mock/tijolo-8-furos.png",
    ativo: true,
  },
  
  // Mais Areia
  {
    id: "p59",
    storeId: "1",
    storeNome: "Construmax",
    nome: "Areia Fina Lavada - m³",
    categoria: "Areia",
    preco: 48.0,
    estoque: 50,
    rating: 4.7,
    imagemUrl: "/mock/areia.png",
    ativo: true,
  },
  {
    id: "p60",
    storeId: "2",
    storeNome: "Casa & Obra",
    nome: "Areia Grossa - m³",
    categoria: "Areia",
    preco: 52.0,
    estoque: 40,
    rating: 4.5,
    imagemUrl: "/mock/areia.png",
    ativo: true,
  },
  {
    id: "p61",
    storeId: "7",
    storeNome: "Ferro & Cimento",
    nome: "Areia de Brita - m³",
    categoria: "Areia",
    preco: 55.0,
    estoque: 35,
    rating: 4.8,
    imagemUrl: "/mock/areia.png",
    ativo: true,
  },
  {
    id: "p62",
    storeId: "8",
    storeNome: "Obra Prima",
    nome: "Areia Peneirada - m³",
    categoria: "Areia",
    preco: 50.5,
    estoque: 45,
    rating: 4.6,
    imagemUrl: "/mock/areia.png",
    ativo: true,
  },
  
  // Mais Argamassa
  {
    id: "p63",
    storeId: "1",
    storeNome: "Construmax",
    nome: "Argamassa AC I 20kg",
    categoria: "Argamassa",
    preco: 12.5,
    estoque: 200,
    rating: 4.5,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p64",
    storeId: "3",
    storeNome: "Materiais Silva",
    nome: "Argamassa AC II 20kg",
    categoria: "Argamassa",
    preco: 14.9,
    estoque: 180,
    rating: 4.7,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p65",
    storeId: "5",
    storeNome: "Mega Materiais",
    nome: "Argamassa AC III 20kg",
    categoria: "Argamassa",
    preco: 16.5,
    estoque: 150,
    rating: 4.8,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p66",
    storeId: "6",
    storeNome: "Construir Mais",
    nome: "Argamassa Polymer 20kg",
    categoria: "Argamassa",
    preco: 18.9,
    estoque: 120,
    rating: 4.9,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  
  // Mais Tinta
  {
    id: "p67",
    storeId: "2",
    storeNome: "Casa & Obra",
    nome: "Tinta Látex Premium Branca 18L",
    categoria: "Tinta",
    preco: 95.0,
    estoque: 45,
    rating: 4.7,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p68",
    storeId: "3",
    storeNome: "Materiais Silva",
    nome: "Tinta Esmalte Sintético Azul 3.6L",
    categoria: "Tinta",
    preco: 45.5,
    estoque: 80,
    rating: 4.6,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p69",
    storeId: "5",
    storeNome: "Mega Materiais",
    nome: "Tinta Epóxi Cinza 3.6L",
    categoria: "Tinta",
    preco: 78.0,
    estoque: 35,
    rating: 4.8,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p70",
    storeId: "8",
    storeNome: "Obra Prima",
    nome: "Tinta Textura Rustica 25kg",
    categoria: "Tinta",
    preco: 120.0,
    estoque: 25,
    rating: 4.9,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  
  // Mais Ferramentas
  {
    id: "p71",
    storeId: "1",
    storeNome: "Construmax",
    nome: "Parafusadeira Elétrica 500W",
    categoria: "Ferramentas",
    preco: 185.0,
    estoque: 15,
    rating: 4.6,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p72",
    storeId: "2",
    storeNome: "Casa & Obra",
    nome: "Furadeira de Impacto 750W",
    categoria: "Ferramentas",
    preco: 220.0,
    estoque: 12,
    rating: 4.7,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p73",
    storeId: "6",
    storeNome: "Construir Mais",
    nome: "Serra Circular 1200W",
    categoria: "Ferramentas",
    preco: 320.0,
    estoque: 8,
    rating: 4.8,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p74",
    storeId: "7",
    storeNome: "Ferro & Cimento",
    nome: "Martelete Perfurador 800W",
    categoria: "Ferramentas",
    preco: 280.0,
    estoque: 10,
    rating: 4.9,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  
  // Mais Blocos
  {
    id: "p75",
    storeId: "1",
    storeNome: "Construmax",
    nome: "Bloco de Concreto Estrutural 14x19x39cm",
    categoria: "Blocos",
    preco: 3.8,
    estoque: 2500,
    rating: 4.7,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p76",
    storeId: "3",
    storeNome: "Materiais Silva",
    nome: "Bloco de Concreto Vedação 9x19x39cm",
    categoria: "Blocos",
    preco: 2.5,
    estoque: 3000,
    rating: 4.6,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p77",
    storeId: "5",
    storeNome: "Mega Materiais",
    nome: "Bloco de Concreto Canaleta 14x19x39cm",
    categoria: "Blocos",
    preco: 4.2,
    estoque: 1800,
    rating: 4.8,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
  {
    id: "p78",
    storeId: "8",
    storeNome: "Obra Prima",
    nome: "Bloco de Concreto Meio 9x19x19cm",
    categoria: "Blocos",
    preco: 1.8,
    estoque: 2200,
    rating: 4.5,
    imagemUrl: "/placeholder.svg",
    ativo: true,
  },
]

export const mockServices: Service[] = [
  {
    id: "s1",
    storeId: "1",
    storeNome: "Construmax",
    nome: "Pedreiro Profissional",
    categoria: "Alvenaria",
    preco: 180,
    precoMinimo: 150,
    precoMaximo: 200,
    tipoPrecificacao: "dia",
    rating: 4.8,
    imagemUrl: "/placeholder.svg",
    ativo: true,
    destacado: true,
    descricao: "Serviço de pedreiro com experiência em construção civil, reformas e acabamentos.",
  },
  {
    id: "s2",
    storeId: "1",
    storeNome: "Construmax",
    nome: "Eletricista Residencial",
    categoria: "Elétrica",
    preco: 80,
    tipoPrecificacao: "hora",
    rating: 4.7,
    imagemUrl: "/placeholder.svg",
    ativo: true,
    descricao: "Instalações elétricas residenciais e comerciais.",
  },
  {
    id: "s3",
    storeId: "2",
    storeNome: "Casa & Obra",
    nome: "Pintura Residencial",
    categoria: "Pintura",
    preco: 35,
    precoMinimo: 30,
    precoMaximo: 45,
    tipoPrecificacao: "m2",
    rating: 4.6,
    imagemUrl: "/placeholder.svg",
    ativo: true,
    descricao: "Pintura interna e externa com materiais de qualidade.",
  },
  {
    id: "s4",
    storeId: "2",
    storeNome: "Casa & Obra",
    nome: "Encanador",
    categoria: "Hidráulica",
    preco: 150,
    tipoPrecificacao: "visita",
    rating: 4.5,
    imagemUrl: "/placeholder.svg",
    ativo: true,
    destacado: true,
    descricao: "Instalação e manutenção de sistemas hidráulicos.",
  },
  {
    id: "s5",
    storeId: "3",
    storeNome: "Materiais Silva",
    nome: "Instalação de Piso",
    categoria: "Acabamento",
    preco: 40,
    precoMinimo: 35,
    precoMaximo: 50,
    tipoPrecificacao: "m2",
    rating: 4.9,
    imagemUrl: "/placeholder.svg",
    ativo: true,
    descricao: "Instalação profissional de pisos cerâmicos e porcelanatos.",
  },
  {
    id: "s6",
    storeId: "3",
    storeNome: "Materiais Silva",
    nome: "Gesseiro",
    categoria: "Acabamento",
    preco: 160,
    tipoPrecificacao: "dia",
    rating: 4.4,
    imagemUrl: "/placeholder.svg",
    ativo: false,
    descricao: "Instalação de gesso, forros e divisórias.",
  },
  {
    id: "s7",
    storeId: "4",
    storeNome: "Depósito Central",
    nome: "Marceneiro",
    categoria: "Marcenaria",
    preco: 3500,
    precoMinimo: 2000,
    precoMaximo: 5000,
    tipoPrecificacao: "projeto",
    rating: 4.8,
    imagemUrl: "/placeholder.svg",
    ativo: true,
    destacado: true,
    descricao: "Projetos personalizados de marcenaria sob medida.",
  },
  {
    id: "s8",
    storeId: "4",
    storeNome: "Depósito Central",
    nome: "Serralheiro",
    categoria: "Serralheria",
    preco: 2500,
    tipoPrecificacao: "projeto",
    rating: 4.3,
    imagemUrl: "/placeholder.svg",
    ativo: true,
    descricao: "Portões, grades e estruturas metálicas.",
  },
]

export const mockReviews: Review[] = [
  {
    id: "r1",
    userNome: "João Silva",
    rating: 5,
    comentario: "Excelente qualidade do cimento, chegou no prazo.",
    productId: "p1",
    storeId: "1",
    status: "aprovado",
    createdAt: "2024-03-20",
  },
  {
    id: "r2",
    userNome: "Maria Santos",
    rating: 4,
    comentario: "Bom produto, mas o preço poderia ser melhor.",
    productId: "p2",
    storeId: "2",
    status: "pendente",
    createdAt: "2024-03-22",
  },
  {
    id: "r3",
    userNome: "Pedro Costa",
    rating: 5,
    comentario: "Melhor preço da região, recomendo!",
    productId: "p3",
    storeId: "3",
    status: "aprovado",
    createdAt: "2024-03-18",
  },
  // Add more reviews...
]

export const mockPlans: Plan[] = [
  {
    id: "plan1",
    nome: "Básico",
    preco: 99.0,
    periodicidade: "mensal",
    recursos: [
      "Perfil profissional no diretório",
      "Receber cotações ilimitadas",
      "Cadastro ilimitado de produtos/serviços",
      "Painel de controle",
      "Relatórios básicos de desempenho",
      "Suporte por email 7 dias/semana"
    ],
    ativo: true,
  },
  {
    id: "plan2",
    nome: "Plus",
    preco: 189.99,
    periodicidade: "mensal",
    recursos: [
      "Tudo do plano Básico",
      "Divulgação automática nas buscas",
      "Destaque nos resultados",
      "Campanhas de marketing mensais",
      "Design de artes digitais",
      "Análises de desempenho",
      "Suporte prioritário"
    ],
    ativo: true,
  },
  {
    id: "plan3",
    nome: "Premium",
    preco: 249.99,
    periodicidade: "mensal",
    recursos: [
      "Tudo do plano Plus",
      "2 vídeos promocionais por mês",
      "Cada vídeo fica 15 dias no ar",
      "Campanhas de marketing semanais",
      "Divulgação em múltiplas plataformas",
      "Suporte prioritário 24/7"
    ],
    ativo: true,
  },
]

export const mockCartItems: CartItem[] = [
  {
    id: "c1",
    productId: "p1",
    storeId: "1",
    qty: 10,
    productNome: "Cimento Portland CP II-E 50kg",
    storeNome: "Construmax",
    precoUnit: 28.9,
  },
  {
    id: "c2",
    productId: "p4",
    storeId: "1",
    qty: 500,
    productNome: "Tijolo Cerâmico 6 Furos 9x14x19cm",
    storeNome: "Construmax",
    precoUnit: 0.85,
  },
  {
    id: "c3",
    productId: "p6",
    storeId: "5",
    qty: 2,
    productNome: "Areia Média Lavada - m³",
    storeNome: "Mega Materiais",
    precoUnit: 45.0,
  },
]

export const mockPurchaseLists: PurchaseList[] = [
  {
    id: "l1",
    nome: "Lista Casa João - Fundação",
    createdAt: "2024-03-15",
    items: mockCartItems,
    observacoes: "Entrega urgente para início da obra",
    totalEstimado: 804.0,
  },
  {
    id: "l2",
    nome: "Reforma Cozinha - Materiais",
    createdAt: "2024-03-10",
    items: [
      {
        id: "c4",
        productId: "p12",
        storeId: "3",
        qty: 2,
        productNome: "Tinta Acrílica Branca 18L",
        storeNome: "Materiais Silva",
        precoUnit: 89.9,
      },
    ],
    observacoes: "Verificar cor exata antes da entrega",
    totalEstimado: 179.8,
  },
]
